### ISSUE TITLE
Cannot find module 'body-parser'

### ISSUE THREAD

**Issue by happyHeartJ** [automat-berlin/node-red-contrib-sipgate#4]
I installed node-red-contrib-sipgate, but something is wrong just like the following :

`@automat-berlin/node-red-contrib-sipgate1.0.0 `
`Error: Cannot find module 'body-parser' (line:5)`
`Error: Cannot find module 'body-parser' (line:5)`
`Error: Cannot find module 'body-parser' (line:5)`
`Error: Cannot find module 'body-parser' (line:3)`
`Error: Cannot find module 'body-parser' (line:5) `
`Error: Cannot find module 'request' (line:3)`

Any body could tell me how to fix it ?

Thx a lot.

**Comment by barinali** [comment]
Hey @happyHeartJ 

Thanks for reporting the missing dependencies. It seems we have forgotten to add the instruction of installing dependencies in the repository folder. If you run `npm install` in the folder where you cloned this repository, it should work.

In the meantime, we are preparing a branch to make the instructions and dependency management better.

**Comment by barinali** [comment]
The issue has been resolved in #5.
